### ISSUE TITLE
Arrays, is this intentional behavior

### ISSUE THREAD

**Issue by timthedevguy** [Edgar-P-yan/xml-class-transformer#5]
Should be my last tidbit :)

I saw your XML sample for arrays was like so:

```xml
<Root>
  <Element1>Value</Element1>
  <Review>stuff</Review>
  <Review>stuff</Review>
</Root>
```
I'm ashamed to say I didn't even know that was possible, I always nested arrays inside a parent tag lol

My XML is as follows:

```xml
<Root>
  <Element1>Value</Element1>
  <Computers>
    <Computer>
      <Name>Machine1</Name>
    </Computer>
    <Computer>
      <Name>Machine2</Name>
    </Computer>
  </Computers>
</Root>
```

Am I correct in understanding that I'll need 3 total classes:

```typescript
@XMLElem({name: 'Root'})
export class RootElement {
  @XMLChildElem({name: 'Element1', type: ()=>String})
  element1: string

  @XMLChildElem({name: 'Computers', type: ()=>ComputersElem})
  computers: ComputersElem
}

@XmlElem({name: 'Computers'})
export class ComputersElem {
  @XMLChildElem({name: 'Computer', type: ()=>ComputerElem, array: true})
  computers: ComputerElem[]
}

@XmlElem({name: 'Computer'})
export class ComputerElem {
  @XmlChildElem({name: 'Name', type: ()=>String})
  name: string
}
```

Then I would access a single computer like so
```typescript
rootElemInstance.computers.computers[0]
```

Do I understand that correctly?  I would love to get it so its like so:

```typescript
rootElemInstance.computers[0]
```
But the XML structure needs preserved.  I've tried a few things and I don't seem to be able to get it to work and I'm not sure if it's lack of my own knowledge in Typescript or just how it is supposed to work.  I'm not asking you to change anything, just wanting confirmation that I'm not missing some cool trick of the library.

I did try something weird which almost worked but then items was a nested array..
```typescript
@XmlElem({ name: 'Computers' })
class ComputersElem<T> implements Iterable<T>, ArrayLike<T> {
  @XmlChildElem({ name: 'Computer', type: () => ComputerElem, array: true })
  private items: T[] = []

  constructor(items?: T[]) {
    console.log('Constructor', this.items)
    if (items) {
      this.items = items
    }
  }
  // constructor(d?: NetworkV1) {
  //   Object.assign(this, d || {})
  // }

  get length(): number {
    return this.items.length
  }

  [index: number]: T

  push(...items: T[]): number {
    return this.items.push(...items)
  }

  pop(): T | undefined {
    return this.items.pop()
  }

  *[Symbol.iterator](): Iterator<T> {
    for (const item of this.items) {
      yield item
    }
  }
}
```
so ComputersElemInstance[0] is an array and that array contains the arary of Computer objects.

**Comment by timthedevguy** [comment]
I looked and looked and the three class method is the best way, and is fine :)  Thank you again for the awesome library!

**Comment by Edgar-P-yan** [comment]
Hi! Sorry for late response. Glad you asked, actually this is something that i myself was not happy about, and it indeed is confusing. This post will help others too, so thanks for bringing this up :)

Yes, this is intentional behaviour, and unfortunately, the best one out there that is able to cover all (or almost all) of the rich and wide variety features of XML, like comments, attributes, arrays without a wrapper tag (surely a strange thing, but Amazon S3 API uses them a lot, and btw I came up with this library at our company where we implement an S3 API compatible storage).

And also this is the way that GoLangs XML implementation works, so i decided to not reinvent the wheel, and just take the approach that proved itself already for many years in Go's community.

So here is an example:
```xml
<article>
	<comments offset="0" take="10">
	  <comment lang="en">comment 1</comment>
	  <comment lang="it">comment 2</comment>
	</comments>
</article>
```

As you see, the container tag `comments` has attributes `offset` and `take`. And tag `comment` has `lang` attr. So the only way to extract all of those fields is to declare three classes:
```ts
class Article {...}
class Comments {
	@XmlAttribute() offset: string,
	@XmlAttribute() take: string,
	@XmlChilElem({ type: ...,  array: true }) comments: Comment[]
}
class Comment {
	@XmlAttribute() lang: string,
	@XmlChardata() content: string,
}
```
